name: Ubuntu-20.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: |
        sudo apt update
        sudo apt install build-essential libgmp-dev z3 libz3-dev opam gcc-aarch64-linux-gnu gcc-riscv64-unknown-elf
        z3 -version
        opam init -y --no-setup --compiler=4.10.0 --shell=sh
        eval `opam config env`
        opam install dune
        git clone https://github.com/rems-project/sail.git
        opam pin -y add sail sail
    - name: Build
      run: |
        eval `opam config env`
        make
        make isla-sail
    - name: Run tests
      run: |
        eval `opam config env`
        make test-github
